import type { Metadata } from "next";
import "./globals.css";
import { WalletProvider } from "@/contexts/wallet-context";
import {DotGothic16} from "next/font/google";


const dotGothic16 = DotGothic16({
  weight: '400',
  subsets: ["latin"],
  display: "swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dotGothic16.className} antialiased`}
      >
        <WalletProvider>
          {children}
        </WalletProvider>
      </body>
    </html>
  );
}
